from __future__ import annotations

from typing import Any

from litellm import completion
from ..exceptions import LLMConfigurationError
from ..prompt import PlannerPrompt


class LiteLLMProvider:
    """
    LiteLLM-backed LLM provider for the AIForge Planner.

    The provider is intentionally responsible only for communicating
    with the LLM. Prompt construction and response validation remain
    separate responsibilities.
    """

    def __init__(
        self,
        model: str,
        *,
        api_key: str | None = None,
        temperature: float = 0.0,
        max_tokens: int | None = None,
    ) -> None:
        if not model.strip():
            raise LLMConfigurationError(
                "LiteLLM model name must not be empty."
            )

        self._model = model
        self._api_key = api_key
        self._temperature = temperature
        self._max_tokens = max_tokens

    def generate(self, prompt: PlannerPrompt) -> str:
        """
        Send a planner prompt to the configured LLM.

        Returns the raw text generated by the provider. Parsing and
        PlannerResult validation are handled by LLMService.
        """

        messages = [
            {
                "role": "system",
                "content": prompt.system,
            },
            {
                "role": "user",
                "content": prompt.user,
            },
        ]

        kwargs: dict[str, Any] = {
            "model": self._model,
            "messages": messages,
            "temperature": self._temperature,
        }

        if self._api_key is not None:
            kwargs["api_key"] = self._api_key

        if self._max_tokens is not None:
            kwargs["max_tokens"] = self._max_tokens
        kwargs["response_format"] = {"type": "json_object"}
        try:
            response = completion(**kwargs)
        except Exception as exc:
            raise RuntimeError(
                f"LiteLLM request failed for model '{self._model}': {exc}"
            ) from exc

        return self._extract_content(response)

    @staticmethod
    def _extract_content(response: Any) -> str:
        try:
            content = response.choices[0].message.content
        except (AttributeError, IndexError, TypeError) as exc:
            raise RuntimeError(
                "LiteLLM returned a response without assistant content."
            ) from exc

        if not isinstance(content, str) or not content.strip():
            raise RuntimeError(
                "LiteLLM returned empty assistant content."
            )

        return content